### ISSUE TITLE
Cannot build with `vercel_edge` preset on windows

### ISSUE THREAD

**Issue by pi0** [unjs/nitro#1664]
Currently we [disable tests for windows](https://github.com/unjs/nitro/blob/main/test/presets/vercel-edge.test.ts#L7) since edge-runetime (by the time i checked) was incomaptible. But there are more issues worth to fix before:

```
 ERROR  Cannot read properties of undefined (reading 'split')                                                 23:56:50

  at /C:/Users/maill/Projects/tmp/test-edge/node_modules/.pnpm/@rollup+plugin-inject@5.0.3_rollup@3.28.1/node_modules/@rollup/plugin-inject/dist/es/index.js:74:74
  at Map.forEach (<anonymous>)
```

(linking from https://github.com/nuxt/nuxt/issues/22875)

**Comment by 1bye** [comment]
The same error, but project not empty:
```
ℹ Building client...                                                                                                17:38:56
ℹ vite v4.3.9 building for production...                                                                            17:38:56
ℹ ✓ 1140 modules transformed.                                                                                       17:39:10   
ℹ .nuxt/dist/client/manifest.json                        7.56 kB │ gzip:   0.94 kB                                  17:39:11
ℹ .nuxt/dist/client/_nuxt/Icon.6f5d80f8.css              0.07 kB │ gzip:   0.09 kB                                  17:39:11   
ℹ .nuxt/dist/client/_nuxt/IconCSS.fe0874d9.css           0.26 kB │ gzip:   0.17 kB                                  17:39:11   
ℹ .nuxt/dist/client/_nuxt/error-500.e798523c.css         2.02 kB │ gzip:   0.75 kB                                  17:39:11   
ℹ .nuxt/dist/client/_nuxt/error-404.95c28eb4.css         3.70 kB │ gzip:   1.14 kB                                  17:39:11   
ℹ .nuxt/dist/client/_nuxt/_uuid_.fc1b7233.css            6.28 kB │ gzip:   1.33 kB                                  17:39:11   
ℹ .nuxt/dist/client/_nuxt/entry.7ff54ced.css           242.98 kB │ gzip:  30.82 kB                                  17:39:11   
ℹ .nuxt/dist/client/_nuxt/auth.81eda7d0.js               0.19 kB │ gzip:   0.17 kB                                  17:39:11   
ℹ .nuxt/dist/client/_nuxt/flow.46011232.js               0.20 kB │ gzip:   0.18 kB                                  17:39:11   
ℹ .nuxt/dist/client/_nuxt/test.ebc7f013.js               0.21 kB │ gzip:   0.19 kB                                  17:39:11   
ℹ .nuxt/dist/client/_nuxt/index.c48f7df6.js              0.23 kB │ gzip:   0.19 kB                                  17:39:11   
ℹ .nuxt/dist/client/_nuxt/confirm.63aa9b5d.js            0.33 kB │ gzip:   0.26 kB                                  17:39:11   
ℹ .nuxt/dist/client/_nuxt/logout.fcf36e2e.js             0.35 kB │ gzip:   0.27 kB                                  17:39:11   
ℹ .nuxt/dist/client/_nuxt/login.d32a023f.js              0.64 kB │ gzip:   0.45 kB                                  17:39:11   
ℹ .nuxt/dist/client/_nuxt/IconCSS.99d47bea.js            0.81 kB │ gzip:   0.52 kB                                  17:39:11   
ℹ .nuxt/dist/client/_nuxt/calculator.b5a8e7ae.js         0.83 kB │ gzip:   0.46 kB                                  17:39:11   
ℹ .nuxt/dist/client/_nuxt/output.6b37c4f6.js             0.88 kB │ gzip:   0.49 kB                                  17:39:11   
ℹ .nuxt/dist/client/_nuxt/if.07f8365d.js                 0.99 kB │ gzip:   0.50 kB                                  17:39:11   
ℹ .nuxt/dist/client/_nuxt/controller.2abf166d.js         1.00 kB │ gzip:   0.53 kB                                  17:39:11   
ℹ .nuxt/dist/client/_nuxt/testnode.ab54fbee.js           1.06 kB │ gzip:   0.53 kB                                  17:39:11   
ℹ .nuxt/dist/client/_nuxt/chatgpt.8b3ba019.js            1.17 kB │ gzip:   0.60 kB                                  17:39:11   
ℹ .nuxt/dist/client/_nuxt/error-500.42160d27.js          1.88 kB │ gzip:   0.99 kB                                  17:39:11   
ℹ .nuxt/dist/client/_nuxt/error-404.b35ab28b.js          2.22 kB │ gzip:   1.14 kB                                  17:39:11   
ℹ .nuxt/dist/client/_nuxt/Icon.50b5242f.js              21.19 kB │ gzip:   8.07 kB                                  17:39:11   
ℹ .nuxt/dist/client/_nuxt/defineShortcuts.7cdd7255.js   41.65 kB │ gzip:  13.97 kB                                  17:39:11   
ℹ .nuxt/dist/client/_nuxt/dashboard.8b0cc1d8.js         60.91 kB │ gzip:  15.77 kB                                  17:39:11   
ℹ .nuxt/dist/client/_nuxt/entry.ce0d97bd.js            337.13 kB │ gzip: 109.63 kB                                  17:39:11   
ℹ .nuxt/dist/client/_nuxt/_uuid_.8ae0067d.js           387.31 kB │ gzip: 123.04 kB                                  17:39:11   
ℹ ✓ built in 14.37s                                                                                                 17:39:11   
✔ Client built in 14385ms                                                                                           17:39:11   
ℹ Building server...                                                                                                17:39:11
ℹ vite v4.3.9 building SSR bundle for production...                                                                 17:39:11
ℹ ✓ 341 modules transformed.                                                                                        17:39:25   
ℹ .nuxt/dist/server/_nuxt/Icon-styles.3c97f940.mjs              0.14 kB                                             17:39:26   
ℹ .nuxt/dist/server/_nuxt/IconCSS-styles.9ba8332f.mjs           0.15 kB                                             17:39:26   
ℹ .nuxt/dist/server/_nuxt/error-404-styles.5437d746.mjs         0.15 kB                                             17:39:26   
ℹ .nuxt/dist/server/_nuxt/error-500-styles.ee00b7aa.mjs         0.15 kB                                             17:39:26   
ℹ .nuxt/dist/server/_nuxt/entry-styles.15b60f07.mjs             0.21 kB                                             17:39:26
ℹ .nuxt/dist/server/styles.mjs                                  0.71 kB                                             17:39:26   
ℹ .nuxt/dist/server/_nuxt/Icon-styles-1.mjs-a085ffd6.js         0.26 kB │ map:   0.11 kB                            17:39:26
ℹ .nuxt/dist/server/_nuxt/IconCSS-styles-1.mjs-54a74734.js      0.46 kB │ map:   0.11 kB                            17:39:26   
ℹ .nuxt/dist/server/_nuxt/entry-styles-2.mjs-638cff50.js        0.57 kB │ map:   0.11 kB                            17:39:26
ℹ .nuxt/dist/server/_nuxt/test-4046bbef.js                      0.68 kB │ map:   0.11 kB                            17:39:26   
ℹ .nuxt/dist/server/_nuxt/auth-eb5f5387.js                      0.85 kB │ map:   0.56 kB                            17:39:26   
ℹ .nuxt/dist/server/_nuxt/island-renderer-9795d38e.js           1.21 kB │ map:   1.39 kB                            17:39:26   
ℹ .nuxt/dist/server/_nuxt/flow-8b3027ab.js                      1.29 kB │ map:   0.14 kB                            17:39:26
ℹ .nuxt/dist/server/_nuxt/confirm-06e1dce7.js                   1.36 kB │ map:   0.62 kB                            17:39:26   
ℹ .nuxt/dist/server/_nuxt/index-51b890e0.js                     1.42 kB │ map:   0.38 kB                            17:39:26   
ℹ .nuxt/dist/server/_nuxt/logout-0bca7734.js                    1.74 kB │ map:   0.51 kB                            17:39:26   
ℹ .nuxt/dist/server/_nuxt/error-500-styles-1.mjs-56d472fe.js    2.23 kB │ map:   0.12 kB                            17:39:26   
ℹ .nuxt/dist/server/_nuxt/IconCSS-c32c0944.js                   2.46 kB │ map:   2.00 kB                            17:39:26   
ℹ .nuxt/dist/server/_nuxt/login-1f3110c6.js                     2.63 kB │ map:   1.35 kB                            17:39:26   
ℹ .nuxt/dist/server/_nuxt/error-500-db36d4dd.js                 3.18 kB │ map:   3.78 kB                            17:39:26   
ℹ .nuxt/dist/server/_nuxt/error-404-styles-1.mjs-0f11a32d.js    3.93 kB │ map:   0.12 kB                            17:39:26   
ℹ .nuxt/dist/server/_nuxt/error-404-ffe34ba1.js                 4.03 kB │ map:   5.82 kB                            17:39:26   
ℹ .nuxt/dist/server/_nuxt/Icon-0b74bf2e.js                      4.60 kB │ map:   3.70 kB                            17:39:26   
ℹ .nuxt/dist/server/_nuxt/index-066ba777.js                    21.43 kB │ map: 269.29 kB                            17:39:26   
ℹ .nuxt/dist/server/_nuxt/dashboard-2bd1ee73.js                27.52 kB │ map:  18.07 kB                            17:39:26   
ℹ .nuxt/dist/server/_nuxt/defineShortcuts-565a6629.js          66.47 kB │ map: 182.49 kB                            17:39:26   
ℹ .nuxt/dist/server/server.mjs                                120.44 kB │ map: 219.53 kB                            17:39:26   
ℹ .nuxt/dist/server/_nuxt/entry-styles-1.mjs-ad4914aa.js      257.58 kB │ map:   0.11 kB                            17:39:26   
ℹ .nuxt/dist/server/_nuxt/entry-styles-3.mjs-46b3fcbd.js      262.16 kB │ map:   0.11 kB                            17:39:26   
ℹ .nuxt/dist/server/_nuxt/_uuid_-d668f854.js                  335.12 kB │ map: 382.17 kB                            17:39:26   
ℹ ✓ built in 15.25s                                                                                                 17:39:26   
✔ Server built in 15271ms                                                                                           17:39:26
✔ Generated public .vercel/output/static                                                                      nitro 17:39:26

 ERROR  Cannot read properties of undefined (reading 'split')                                                        17:39:26  

  at /C:/--PROJECT--/Flow/node_modules/@rollup/plugin-inject/dist/es/index.js:74:74
  at Map.forEach (<anonymous>)
  at inject (/C:/--PROJECT--/Flow/node_modules/@rollup/plugin-inject/dist/es/index.js:71:16)
  at getRollupConfig (/C:/--PROJECT--/Flow/node_modules/nuxt/node_modules/nitropack/dist/shared/nitro.7a525996.mjs:1849:29)    
  at build (/C:/--PROJECT--/Flow/node_modules/nuxt/node_modules/nitropack/dist/shared/nitro.7a525996.mjs:2123:24)
  at /C:/--PROJECT--/Flow/node_modules/nuxt/dist/index.mjs:2643:13
  at async build (/C:/--PROJECT--/Flow/node_modules/nuxt/dist/index.mjs:3794:5)
  at async Object.invoke (/C:/--PROJECT--/Flow/node_modules/nuxi/dist/chunks/build.mjs:59:5)
  at async _main (/C:/--PROJECT--/Flow/node_modules/nuxi/dist/cli.mjs:49:20)
```

**Comment by pontsci** [comment]
Same here, just broke when I moved to Nuxt 3.8.2 and updated dependencies. Vercel edge preset is throwing this exact same error.

**Comment by pi0** [comment]
@pontsci Are you using windows? Using WSL2 might be a workaround if really need to build locally.

**Comment by RihanArfan** [comment]
In Nitro v3 we have removed the deprecated `vercel-edge` preset
