### ISSUE TITLE
improve pre-render error output

### ISSUE THREAD

**Issue by Hebilicious** [unjs/nitro#1675]
### Describe the feature

Currently trying to pre-render a nuxt content project

```
Errors prerendering:
  ├─ / (1108ms)                                                                                                        nitro 4:44:39 PM
  │ ├── Error: [500] 
  │ └── Linked from /playground
  │ └── Linked from /get-started/installation
  │ └── Linked from /get-started/introduction
  │ └── Linked from /usage/form-actions
  │ └── Linked from /usage/server-loaders
  │ └── Linked from /usage/advanced
  │ └── Linked from /integrations/server-block
  │ └── Linked from /integrations/validation-libraries
                                                                                                                       nitro 4:44:39 PM

 ERROR  Exiting due to prerender errors.                                                                                     4:44:39 PM

  at prerender (/Users/hebilicious/GitHub/form-actions-nuxt/node_modules/nitropack/dist/shared/nitro.7d994942.mjs:211:11)
  at async /Users/hebilicious/GitHub/form-actions-nuxt/node_modules/nuxt/dist/index.mjs:2852:7
  at async build (/Users/hebilicious/GitHub/form-actions-nuxt/node_modules/nuxt/dist/index.mjs:4170:5)
  at async Object.run (/Users/hebilicious/GitHub/form-actions-nuxt/node_modules/nuxi/dist/chunks/build.mjs:99:5)
  at async runCommand$1 (/Users/hebilicious/GitHub/form-actions-nuxt/node_modules/nuxi/dist/shared/nuxi.c627b411.mjs:1644:5)
  at async runCommand$1 (/Users/hebilicious/GitHub/form-actions-nuxt/node_modules/nuxi/dist/shared/nuxi.c627b411.mjs:1638:7)
  at async runMain$1 (/Users/hebilicious/GitHub/form-actions-nuxt/node_modules/nuxi/dist/shared/nuxi.c627b411.mjs:1756:7) 
  ```
  
  These errors are not helpful 😓 

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Please, use reproductions. I appreciate your feedback to improve errors nut even have no idea how this 500 error happened...

**Comment by Hebilicious** [comment]
@pi0 I'm working on a reproduction. This is more about ways that we could improve the prerender error output.

**Comment by pi0** [comment]
Surely, if possible. `Error: [500]` indicated there was an error without an explicit message. I like to know the source of it.

**Comment by pi0** [comment]
Normally nitro shows 500 error stacks now

<img width="738" alt="image" src="https://github.com/user-attachments/assets/e354b3fd-df1f-44a8-997f-6c2c5f07c532">
