### ISSUE TITLE
realative wasm imports not resolving properly

### ISSUE THREAD

**Issue by mukundshah** [unjs/nitro#1971]
### Environment

- Operating System: `Darwin`
- Node Version:     `v21.2.0`
- Nitro Version:    `2.8.1`
- Package Manager:  `pnpm@8.11.0`

### Reproduction

Repo: https://github.com/mukundshah/nitro-wasm

1. Build project with cloudflare-pages or cloudflare-modules preset
```shell
pnpm build --preset cloudflare_pages # or cloudflare_modules
```
2.  Run wrangler dev. At this point, it will fail because of import error.
3. Move the `wasm` directory from `routes` to root of project and build again for cloudflare-pages or cloudflare-modules preset. This time it will work.

### Describe the bug

```sh
    .wrangler/tmp/pages-GdnL2R/chunks/index.mjs:1:263:
      1 │ ...(s,{})).exports}(import("./wasm/sum.wasm"));return a((()=>`2+3=$...
        ╵                            ~~~~~~~~~~~~~~~~~
 ```
 
 When relative paths are used to import wasm, the bundler is not resolving the path properly.
 
 
![image](https://github.com/unjs/nitro/assets/39938037/5e5f71cc-0d66-4838-9e37-dc0662f35742)

Here, wasms are within the `/routes` directory and in `index.ts`
```ts
export default defineLazyEventHandler(async () => {
  const { sum } = await importWasm(import("./wasm/sum.wasm" as string));
  return eventHandler(() => {
    return `2+3=${sum(2, 3)}`;
  });
});
```
it's being relatively imported.

It works if I move the wasm to root directory

### Logs

```sh
✘ [ERROR] ENOENT: no such file or directory, open '/Users/mukund/Developer/play/nitro-wasm/.wrangler/tmp/pages-2jOYhf/chunks/wasm/sum.wasm' [plugin wrangler-module-collector]

    ../../../../../usr/local/lib/node_modules/wrangler/node_modules/esbuild/lib/main.js:1360:21:
      1360 │         let result = await callback({
           ╵                      ^

    at async open (node:internal/fs/promises:628:25)
    at async readFile (node:internal/fs/promises:1228:14)
    at async /usr/local/lib/node_modules/wrangler/wrangler-dist/cli.js:123326:37
    at async requestCallbacks.on-resolve (/usr/local/lib/node_modules/wrangler/node_modules/esbuild/lib/main.js:1360:22)
    at async handleRequest (/usr/local/lib/node_modules/wrangler/node_modules/esbuild/lib/main.js:723:13)

  This error came from the "onResolve" callback registered here:

    ../../../../../usr/local/lib/node_modules/wrangler/wrangler-dist/cli.js:123282:19:
      123282 │             build5.onResolve(
             ╵                    ~~~~~~~~~

    at /usr/local/lib/node_modules/wrangler/wrangler-dist/cli.js:123282:20
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/wrangler/wrangler-dist/cli.js:123281:22
    at Array.forEach (<anonymous>)
    at setup (/usr/local/lib/node_modules/wrangler/wrangler-dist/cli.js:123277:28)
    at handlePlugins (/usr/local/lib/node_modules/wrangler/node_modules/esbuild/lib/main.js:1279:21)
    at buildOrContextImpl (/usr/local/lib/node_modules/wrangler/node_modules/esbuild/lib/main.js:968:5)
    at Object.buildOrContext (/usr/local/lib/node_modules/wrangler/node_modules/esbuild/lib/main.js:776:5)
    at /usr/local/lib/node_modules/wrangler/node_modules/esbuild/lib/main.js:2172:68

  The plugin "wrangler-module-collector" was triggered by this import

    .wrangler/tmp/pages-2jOYhf/chunks/index.mjs:1:263:
      1 │ ...(s,{})).exports}(import("./wasm/sum.wasm"));return a((()=>`2+3=$...
        ╵                            ~~~~~~~~~~~~~~~~~


/usr/local/lib/node_modules/wrangler/wrangler-dist/cli.js:29374
            throw a;
            ^

Error: Failed to build
    at bundleWorker (/usr/local/lib/node_modules/wrangler/wrangler-dist/cli.js:123692:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async build (/usr/local/lib/node_modules/wrangler/wrangler-dist/cli.js:149790:61)

Node.js v21.2.0
```

**Comment by pi0** [comment]
It should be resolved in nightly channel.

**Comment by mukundshah** [comment]
Yes. It's resolved. Thank you @pi0.
I will now delete the reproduction repo.
