### ISSUE TITLE
 ERROR  Rollup error:  Cannot read properties of null (reading 'included')   

### ISSUE THREAD

**Issue by vencho-mdp** [unjs/nitro#200]
### Environment

Nitro: Latest
Node: v16.14.2

### Reproduction

Go to the Nitro Playground and Run `nitro dev`

Or check on Stackblitz: https://stackblitz.com/github/unjs/nitro/tree/main/examples/hello-world?file=package.json

### Describe the bug

No index route is generated plus the error above is shown in the console

### Logs

```sh
ERROR  Rollup error:  Cannot read properties of null (reading 'included')                 nitro 19:01:34

  at Module.isIncluded (node_modules/rollup/dist/es/shared/rollup.js:12683:25)
  at eval (node_modules/rollup/dist/es/shared/rollup.js:16138:17)
  at Array.filter (<anonymous>)
  at getIncludedModules (node_modules/rollup/dist/es/shared/rollup.js:16137:38)
  at Bundle.generateChunks (node_modules/rollup/dist/es/shared/rollup.js:16083:40)
  at async Bundle.generate (node_modules/rollup/dist/es/shared/rollup.js:15960:28)
  at async eval (node_modules/rollup/dist/es/shared/rollup.js:23682:27)
  at async catchUnfinishedHookActions (node_modules/rollup/dist/es/shared/rollup.js:23041:20)
  at async Promise.all (index 0)
  at async Task.run (node_modules/rollup/dist/es/shared/watch.js:4958:32)
```
```

**Comment by justindasilva** [comment]
I have the same issue. 
![Screen Shot 2022-05-06 at 3 14 06 PM](https://user-images.githubusercontent.com/882534/167203180-2f611b45-df2b-483d-97cd-5917b7d879a6.png)

The server eventually runs though.

**Comment by johannschopplich** [comment]
Same error here. Using pnpm.

**Comment by vencho-mdp** [comment]
this seems to be working now with the latest version of nitro. kind of weird

**Comment by darklight9811** [comment]
@vencho-mdp this is still happening to me

**Comment by vencho-mdp** [comment]
What happens if you set your node version to 16.x?

**Comment by darklight9811** [comment]
@vencho-mdp 16.10.0 breaks, 16.13.1 works
