### ISSUE TITLE
x-forwared-for error on stackblitz

### ISSUE THREAD

**Issue by samydoesit** [unjs/nitro#2197]
### Environment

"nuxt": "^3.10.3",
"nitro": "2.9.0"

### Reproduction

https://stackblitz.com/edit/github-jnmnbt?file=README.md

### Describe the bug

A new Nuxt Starter on Stackblitz via [nuxt.new](nuxt.new) leads to an error - nothing will be rendered. (undefined - x-forwared-for)

```
 ERROR  [uncaughtException] Invalid value "undefined" for header "x-forwarded-for"  
```

Downgrading `nitropack` to 2.8.1 fixes the issue.

### Logs

```sh
ERROR  [uncaughtException] Invalid value "undefined" for header "x-forwarded-for"                        10:57:09

  at __node_internal_ (https://githubjnmnbt-om4n.w-credentialless-staticblitz.com/blitz.c9a8a620.js:36:5406)
  at new <anonymous> (https://githubjnmnbt-om4n.w-credentialless-staticblitz.com/blitz.c9a8a620.js:36:4168)
  at __node_internal_ (https://githubjnmnbt-om4n.w-credentialless-staticblitz.com/blitz.c9a8a620.js:184:8336)
  at OutgoingMessage.appendHeader (https://githubjnmnbt-om4n.w-credentialless-staticblitz.com/blitz.c9a8a620.js:184:8963)
  at ProxyServer.eval (node_modules/nitropack/dist/chunks/server.mjs:342:16)
  at EventEmitter.emit (https://githubjnmnbt-om4n.w-credentialless-staticblitz.com/blitz.c9a8a620.js:42:9202)
  at ClientRequest.eval (node_modules/httpxy/dist/index.mjs:272:16)
  at EventEmitter.emit (https://githubjnmnbt-om4n.w-credentialless-staticblitz.com/blitz.c9a8a620.js:42:9202)
  at https://githubjnmnbt-om4n.w-credentialless-staticblitz.com/blitz.c9a8a620.js:252:11492
  at onSocketNT (https://githubjnmnbt-om4n.w-credentialless-staticblitz.com/blitz.c9a8a620.js:252:11509)
```
```

**Comment by manniL** [comment]
@pi0 (sorry for the ping but rather urgent) - sent a PR fixing this in #2198

**Comment by pi0** [comment]
Thanks for the report and PR. It will be fixed in a patch release however it is strange that stackblitz is not setting this header (according to the [Node.js docs](https://nodejs.org/api/net.html#socketremoteaddress) it shall be undefined but when socket is destroyed).  

It also made issues in other places such as crossws.unjs.io when testing on stackblitz.
