### ISSUE TITLE
$fetch 'DELETE': 500 (Internal Server Error)

### ISSUE THREAD

**Issue by kssion** [unjs/nitro#2349]
### Environment

Nitro 2.9.4

### Reproduction

$fetch('/api/web/images/del/123456', {method: 'DELETE'})

### Describe the bug

nuxt.config.ts
```
routeRules: {
  '/api/**': {
    proxy: 'http://127.0.0.1:3600/api/**'
  }
}
```

DeleteImageModal.vue
```
$fetch('/api/web/images/del/123456', {method: 'DELETE'})
```

This issue only occurs with 'DELETE' requests.

### Logs

```sh
# browser console output:
catch FetchError: [DELETE] "/api/web/images/del/123456": 500 Internal Server Error
    at async $fetch22 (ofetch.37386b05.mjs:268:15)

# Nuxt3 console:
 ERROR  [nuxt] [request error] [unhandled] [500] fetch failed
  at Object.fetch (node:internal/deps/undici/undici:11372:11)  
  at async sendProxy (./node_modules/h3/dist/index.mjs:1157:20)  
  at async ./node_modules/h3/dist/index.mjs:1962:19  
  at async Object.callAsync (./node_modules/unctx/dist/index.mjs:72:16)  
  at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:2249:7)
```

**Comment by kssion** [comment]
Upgrading to 2.9.6 is no problem now.
