### ISSUE TITLE
Deno preset

### ISSUE THREAD

**Issue by pi0** [unjs/nitro#422]
(not same as `deno-deploy`)

We can have a new preset for deno to make output working with `deno` CLI. 

The main catch, is that we need to transform imports to nitro. We could either continue working on [rollup-plugin-node-deno](https://github.com/unjs/rollup-plugin-node-deno) or inline transform into preset.

**Comment by bartlomieju** [comment]
Hi, Bartek from the Deno team here.

What is the problem with imports you are facing? We have been working on improving our Node compatibility significantly in the recent weeks and it feels like there might not be a need to transform imports anymore.

Let me know if there's something the Deno team could help you with.

**Comment by so1ve** [comment]
It seems that the readAsset function is not implemented?

**Comment by oceaann** [comment]
> > Hi, Bartek from the Deno team here.
> > What is the problem with imports you are facing? We have been working on improving our Node compatibility significantly in the recent weeks and it feels like there might not be a need to transform imports anymore.
> > Let me know if there's something the Deno team could help you with.
> 
> I tried running `deno task dev`
> 
> ```js
> error: Dir F:\geohints\geohints\node_modules\.deno\unimport@3.0.6\node_modules\unimport\dist to F:\geohints\geohints\node_modules\.deno\unimport@3.0.6_1\node_modules\unimport\dist
> 
> Caused by:
>     0: Hard linking F:\geohints\geohints\node_modules\.deno\unimport@3.0.6\node_modules\unimport\dist\addons.cjs to F:\geohints\geohints\node_modules\.deno\unimport@3.0.6_1\node_modules\unimport\dist\addons.cjs
>     1: Incorrect function. (os error 1)
> ```


For some reason there is `\unimport@3.0.6\` trying to import things from `\unimport@3.0.6_1\` -  @bartlomieju I think its the reason why it doesn't work

**Comment by bartlomieju** [comment]
@oceaann this issue should be solved by https://github.com/denoland/deno/pull/18824

**Comment by oceaann** [comment]
> @oceaann this issue should be solved by [denoland/deno#18824](https://github.com/denoland/deno/pull/18824)

I used `deno upgrade --canary` and exact same error (after running `deno task dev` on nuxt project
```js
error: Dir F:\geohints\geohints\node_modules\.deno\unimport@3.0.6\node_modules\unimport\dist to F:\geohints\geohints\node_modules\.deno\unimport@3.0.6_1\node_modules\unimport\dist

Caused by:
    0: Hard linking F:\geohints\geohints\node_modules\.deno\unimport@3.0.6\node_modules\unimport\dist\addons.cjs to F:\geohints\geohints\node_modules\.deno\unimport@3.0.6_1\node_modules\unimport\dist\addons.cjs
    1: Incorrect function. (os error 1)
```

**Comment by oceaann** [comment]
```js
D:\custom-frontend>deno task dev
Warning Currently only basic package.json `scripts` are supported. Programs like `rimraf` or `cross-env` will not work correctly. This will be fixed in an upcoming release.
Task dev nuxt dev
error: Uncaught TypeError: Windows only supports ctrl-c (SIGINT) and ctrl-break (SIGBREAK).
    at bindSignal (ext:runtime/40_signals.js:16:14)
    at Object.addSignalListener (ext:runtime/40_signals.js:56:19)
    at process.on (ext:deno_node/process.ts:306:22)
    at startSubprocess (file:///D:/custom-frontend/node_modules/.deno/nuxt@3.3.3/node_modules/nuxi/dist/cli-wrapper.mjs:22:11)
    at file:///D:/custom-frontend/node_modules/.deno/nuxt@3.3.3/node_modules/nuxi/dist/cli-wrapper.mjs:7:3
```
New error 😕

**Comment by bartlomieju** [comment]
@oceaann sorry for a slow response, this notification went into oblivion of the inbox. Have you folks worked around ti somehow?
