### ISSUE TITLE
`Cannot find module xxx` on build

### ISSUE THREAD

**Issue by warflash** [unjs/nitro#528]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.13.2`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@8.13.2`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

npm run build goes through just fine on stackblitz: https://stackblitz.com/edit/github-ouxssx-ltdrim?file=pages%2Findex.vue
however downloading the repo and trying to build on windows results in `Cannot find module xxx` on build

### Describe the bug

See above

### Logs

```sh
i Client built in 7088ms                                                                                                                                                                               23:32:55
i Building server...                                                                                                                                                                                   23:32:55  
√ Server built in 660ms                                                                                                                                                                                23:32:55
√ Generated public .output/public                                                                                                                                                                nitro 23:32:55
i Building Nitro Server (preset: node)                                                                                                                                                           nitro 23:32:55

 ERROR  (node:31500) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./regenerator/" in the "exports" field module resolution of the package at E:\Downloads\github-ouxssx-ltdrim\node_modules\@babel\runtime\package.json imported from E:\Downloads\github-ouxssx-ltdrim\node_modules.
Update this package.json to use a subpath pattern like "./regenerator/*".
(Use `node --trace-deprecation ...` to show where the warning was created)


 ERROR                                                                                                                                                                                           nitro 23:33:58  

undefined


 ERROR  Error: Cannot find module gl-matrix/vec4 imported from file:///E:/Downloads/github-ouxssx-ltdrim/node_modules, file:///E:/Downloads/github-ouxssx-ltdrim/node_modules/nuxt/node_modules, file:///E:/Downloads/github-ouxssx-ltdrim/node_modules/nitropack/node_modules, file:///E:/Downloads/github-ouxssx-ltdrim/, file:///E:/Downloads/github-ouxssx-ltdrim/node_modules/_index.js, file:///E:/Downloads/github-ouxssx-ltdrim/node_modules, file:///E:/Downloads/github-ouxssx-ltdrim/node_modules/nuxt/, file:///E:/Downloads/github-ouxssx-ltdrim/node_modules/nuxt/node_modules/_index.js, file:///E:/Downloads/github-ouxssx-ltdrim/node_modules/nuxt/node_modules, file:///E:/Downloads/github-ouxssx-ltdrim/node_modules/nitropack/, file:///E:/Downloads/github-ouxssx-ltdrim/node_modules/nitropack/node_modules/_index.js, file:///E:/Downloads/github-ouxssx-ltdrim/node_modules/nitropack/node_modules

  at resolvePath (/E:/Downloads/github-ouxssx-ltdrim/node_modules/mlly/dist/index.mjs:1079:10)
  at _resolve (/E:/Downloads/github-ouxssx-ltdrim/node_modules/nitropack/dist/shared/nitro.9c828268.mjs:306:22)
  at Object.resolveId (/E:/Downloads/github-ouxssx-ltdrim/node_modules/nitropack/dist/shared/nitro.9c828268.mjs:350:34)
  at async resolveId (/E:/Downloads/github-ouxssx-ltdrim/node_modules/rollup/dist/es/shared/rollup.js:21737:26)
  at async ModuleLoader.resolveId (/E:/Downloads/github-ouxssx-ltdrim/node_modules/rollup/dist/es/shared/rollup.js:22037:19)
  at async /E:/Downloads/github-ouxssx-ltdrim/node_modules/@rollup/plugin-commonjs/dist/es/index.js:773:14
  at async Promise.all (index 14)
  at async /E:/Downloads/github-ouxssx-ltdrim/node_modules/@rollup/plugin-commonjs/dist/es/index.js:765:30
  at async rewriteRequireExpressionsAndGetImportBlock (/E:/Downloads/github-ouxssx-ltdrim/node_modules/@rollup/plugin-commonjs/dist/es/index.js:1312:28)
  at async transformCommonjs (/E:/Downloads/github-ouxssx-ltdrim/node_modules/@rollup/plugin-commonjs/dist/es/index.js:1874:23)
```

**Comment by Marstonchan** [comment]
m

**Comment by Marstonchan** [comment]
i got this error too, but it still successfully built

**Comment by warflash** [comment]
@Marstonchan That's interesting. Are you also using gl-matrix/deck.gl or did it happen with a different package for you? Sadly builds don't go through for me after the error :/

**Comment by pi0** [comment]
Hi. Closing issue as it seems stalled for a while (sorry!). If you experience similar issues please use a fresh issue+reproduction 🙏🏼
