### ISSUE TITLE
Need a more detailed documentation.

### ISSUE THREAD

**Issue by eduplessis** [unjs/nitro#551]
### Environment

Node v18.9.0
npm v8.19.1

Do exactly what the doc say.

Sorry if it's feel little bit wrong and I don't want to put pressure on you. You are doing a suppppperb job with all of the unjs package and Nuxt too.

### Reproduction

Do exactly what the doc say

### Cannot detect workspace root
when following the getting started guide. 

![image](https://user-images.githubusercontent.com/398245/194577625-4d30dd9f-9b1d-4806-affd-462fd5f4019f.png)

### Logs

```sh
Error: Cannot detect workspace root from /home/eduplessis/nitro-app
    at findWorkspaceDir (file:///home/eduplessis/.npm/_npx/c367e59d342c6fbd/node_modules/pkg-types/dist/index.mjs:117:9)
    at async loadOptions (file:///home/eduplessis/.npm/_npx/c367e59d342c6fbd/node_modules/nitropack/dist/shared/nitro.9c828268.mjs:2271:26)
    at async createNitro (file:///home/eduplessis/.npm/_npx/c367e59d342c6fbd/node_modules/nitropack/dist/shared/nitro.9c828268.mjs:2347:19)
    at async main (file:///home/eduplessis/.npm/_npx/c367e59d342c6fbd/node_modules/nitropack/dist/cli.mjs:65:19)
```

**Comment by danielroe** [comment]
Have you run an `npm install`?
