### ISSUE TITLE
Deploying on render-com Maximum call stack size exceeded

### ISSUE THREAD

**Issue by no1621name** [unjs/nitro#668]
### Environment

nitropack - 1.0.0
node - idk which version render.com uses

### Reproduction

[repo](https://github.com/no1621name/cheesy-api)

### Describe the bug

I'm trying to deploy my api on render.com, but I got RangeError: Maximum call stack size exceeded from jiti and mlly (check the logs). Commands for build: npm i && npx nitropack build 

### Logs

```sh
Nov. 16 07:38:52 PM  ==> Cloning from https://github.com/no1621name/cheesy-api...
Nov. 16 07:38:52 PM  ==> Checking out commit e2f47c161a654cf9fda61fa26a37e21d48449048 in branch master
Nov. 16 07:38:56 PM  ==> Downloading cache...
Nov. 16 07:39:11 PM  ==> Transferred 131MB in 10s. Extraction took 3s.
Nov. 16 07:39:14 PM  ==> Running build command 'npm i && npx nitropack build'...
Nov. 16 07:39:20 PM  audited 676 packages in 4.634s
Nov. 16 07:39:20 PM  
Nov. 16 07:39:20 PM  80 packages are looking for funding
Nov. 16 07:39:20 PM    run `npm fund` for details
Nov. 16 07:39:20 PM  
Nov. 16 07:39:20 PM  found 0 vulnerabilities
Nov. 16 07:39:20 PM  
Nov. 16 07:39:44 PM  RangeError: Maximum call stack size exceeded
Nov. 16 07:39:44 PM      at jiti (/opt/render/project/src/node_modules/jiti/dist/jiti.js:1:247662)
Nov. 16 07:39:44 PM      at /opt/render/project/src/node_modules/mlly/dist/index.cjs:3:15
Nov. 16 07:39:44 PM      at jiti (/opt/render/project/src/node_modules/jiti/dist/jiti.js:1:247502)
Nov. 16 07:39:44 PM      at /opt/render/project/src/node_modules/pkg-types/dist/index.mjs:3:13
Nov. 16 07:39:44 PM      at jiti (/opt/render/project/src/node_modules/jiti/dist/jiti.js:1:247502)
Nov. 16 07:39:44 PM      at /opt/render/project/src/node_modules/mlly/dist/index.cjs:16:18
Nov. 16 07:39:44 PM      at jiti (/opt/render/project/src/node_modules/jiti/dist/jiti.js:1:247502)
Nov. 16 07:39:44 PM      at /opt/render/project/src/node_modules/pkg-types/dist/index.mjs:3:13
Nov. 16 07:39:44 PM      at jiti (/opt/render/project/src/node_modules/jiti/dist/jiti.js:1:247502)
Nov. 16 07:39:44 PM      at /opt/render/project/src/node_modules/mlly/dist/index.cjs:16:18
Nov. 16 07:39:44 PM      at jiti (/opt/render/project/src/node_modules/jiti/dist/jiti.js:1:247502)
Nov. 16 07:39:44 PM      at /opt/render/project/src/node_modules/pkg-types/dist/index.mjs:3:13
Nov. 16 07:39:44 PM      at jiti (/opt/render/project/src/node_modules/jiti/dist/jiti.js:1:247502)
Nov. 16 07:39:44 PM      at /opt/render/project/src/node_modules/mlly/dist/index.cjs:16:18
Nov. 16 07:39:44 PM      at jiti (/opt/render/project/src/node_modules/jiti/dist/jiti.js:1:247502)
Nov. 16 07:39:44 PM      at /opt/render/project/src/node_modules/pkg-types/dist/index.mjs:3:13
Nov. 16 07:39:44 PM      at jiti (/opt/render/project/src/node_modules/jiti/dist/jiti.js:1:247502)
Nov. 16 07:39:44 PM      at /opt/render/project/src/node_modules/mlly/dist/index.cjs:16:18
Nov. 16 07:39:44 PM      at jiti (/opt/render/project/src/node_modules/jiti/dist/jiti.js:1:247502)
Nov. 16 07:39:44 PM      at /opt/render/project/src/node_modules/pkg-types/dist/index.mjs:3:13
Nov. 16 07:39:44 PM      at jiti (/opt/render/project/src/node_modules/jiti/dist/jiti.js:1:247502)
Nov. 16 07:39:44 PM      at /opt/render/project/src/node_modules/mlly/dist/index.cjs:16:18
Nov. 16 07:39:44 PM      at jiti (/opt/render/project/src/node_modules/jiti/dist/jiti.js:1:247502)
Nov. 16 07:39:44 PM      at /opt/render/project/src/node_modules/pkg-types/dist/index.mjs:3:13
Nov. 16 07:39:44 PM      at jiti (/opt/render/project/src/node_modules/jiti/dist/jiti.js:1:247502)
Nov. 16 07:39:44 PM      at /opt/render/project/src/node_modules/mlly/dist/index.cjs:16:18
Nov. 16 07:39:44 PM      at jiti (/opt/render/project/src/node_modules/jiti/dist/jiti.js:1:247502)
Nov. 16 07:39:44 PM      at /opt/render/project/src/node_modules/pkg-types/dist/index.mjs:3:13
Nov. 16 07:39:44 PM      at jiti (/opt/render/project/src/node_modules/jiti/dist/jiti.js:1:247502)
Nov. 16 07:39:44 PM      at /opt/render/project/src/node_modules/mlly/dist/index.cjs:16:18
Nov. 16 07:39:44 PM      at jiti (/opt/render/project/src/node_modules/jiti/dist/jiti.js:1:247502)
Nov. 16 07:39:44 PM      at /opt/render/project/src/node_modules/pkg-types/dist/index.mjs:3:13
Nov. 16 07:39:44 PM      at jiti (/opt/render/project/src/node_modules/jiti/dist/jiti.js:1:247502)
Nov. 16 07:39:44 PM      at /opt/render/project/src/node_modules/mlly/dist/index.cjs:16:18
Nov. 16 07:39:44 PM      at jiti (/opt/render/project/src/node_modules/jiti/dist/jiti.js:1:247502)
Nov. 16 07:39:44 PM      at /opt/render/project/src/node_modules/pkg-types/dist/index.mjs:3:13
Nov. 16 07:39:44 PM      at jiti (/opt/render/project/src/node_modules/jiti/dist/jiti.js:1:247502)
Nov. 16 07:39:44 PM      at /opt/render/project/src/node_modules/mlly/dist/index.cjs:16:18
Nov. 16 07:39:44 PM      at jiti (/opt/render/project/src/node_modules/jiti/dist/jiti.js:1:247502)
Nov. 16 07:39:44 PM      at /opt/render/project/src/node_modules/pkg-types/dist/index.mjs:3:13
Nov. 16 07:39:44 PM      at jiti (/opt/render/project/src/node_modules/jiti/dist/jiti.js:1:247502)
Nov. 16 07:39:44 PM      at /opt/render/project/src/node_modules/mlly/dist/index.cjs:16:18
Nov. 16 07:39:44 PM      at jiti (/opt/render/project/src/node_modules/jiti/dist/jiti.js:1:247502)
Nov. 16 07:39:44 PM      at /opt/render/project/src/node_modules/pkg-types/dist/index.mjs:3:13
Nov. 16 07:39:44 PM      at jiti (/opt/render/project/src/node_modules/jiti/dist/jiti.js:1:247502)
Nov. 16 07:39:44 PM      at /opt/render/project/src/node_modules/mlly/dist/index.cjs:16:18
Nov. 16 07:39:44 PM      at jiti (/opt/render/project/src/node_modules/jiti/dist/jiti.js:1:247502)
Nov. 16 07:39:44 PM      at /opt/render/project/src/node_modules/pkg-types/dist/index.mjs:3:13
Nov. 16 07:39:44 PM      at jiti (/opt/render/project/src/node_modules/jiti/dist/jiti.js:1:247502)
Nov. 16 07:39:44 PM      at /opt/render/project/src/node_modules/mlly/dist/index.cjs:16:18
Nov. 16 07:39:44 PM  ==> Build failed 😞
Nov. 16 07:39:44 PM  ==> Generating container image from build. This may take a few minutes...
```

**Comment by platform-kit** [comment]
I am seeing the same thing both on render and locally using nitropack dev on the first route example (hello world) from the docs. Very frustrating. I don't understand how Nuxt has adopted Nitro when it is seemingly in disarray (or perhaps, just poorly documented).

**Comment by manniL** [comment]
@platform-kit I can't reproduce it locally neither in dev nor in build.

@no1621name Could you boil down your repo to a *minimal* reproduction?

**Comment by platform-kit** [comment]
Sorry, can't help, this was 2 years ago...
